version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  assignees:
  - Ray-Eldath
  ignore:
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - ">= 1.12.a, < 1.13"
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - "> 1.2.1, < 1.3"
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - "> 1.5.0, < 1.6"
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - "> 1.7.0, < 1.8"
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - ">= 3.11.a, < 3.12"
  - dependency-name: org.jetbrains.dokka
    versions:
    - "> 0.10.0, < 1"
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - "> 1.3.71, < 1.4"
  - dependency-name: org.jetbrains.kotlin.kapt
    versions:
    - "> 1.3.71, < 1.4"
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - "> 5.5.1, < 5.6"
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - "> 5.6.1, < 5.7"
  - dependency-name: jvm
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: kapt
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.dokka
    versions:
    - 1.4.20
    - 1.4.30
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.27"
    - "1.28"
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.27"
    - "1.28"
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - 1.15.0
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.10"
  - dependency-name: org.json:json
    versions:
    - "20201115"
