# @formatter:off
version: 2
jobs:
    dependencies:
        docker:
            - image: circleci/openjdk:11.0.4-jdk-stretch
        steps:
            - checkout
            - restore_cache:
                key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - restore_cache:
                key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
            - run:
                name: Chmod Permissions
                command: sudo chmod +x ./gradlew
            - run:
                  name: Lint
                  command: ./gradlew detekt
            - store_artifacts:
                  path: build/reports/detekt
                  destination: detekt
            - save_cache:
                paths:
                    - ~/.gradle/wrapper
                key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - save_cache:
                paths:
                    - ~/.gradle/caches
                key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
    build:
        docker:
            - image: circleci/openjdk:11.0.4-jdk-stretch
        steps:
            - checkout
            - restore_cache:
                key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - restore_cache:
                key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
            - run:
                name: Chmod Permissions
                command: sudo chmod +x ./gradlew
            - run:
                name: Build
                command: ./gradlew build
    jmh:
        docker:
            - image: circleci/openjdk:11.0.4-jdk-stretch
        steps:
            - checkout
            - restore_cache:
                key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - restore_cache:
                key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
            - run:
                name: Chmod Permissions
                command: sudo chmod +x ./gradlew
            - run:
                name: JMH Test
                command: ./gradlew jmh
            #- run:
            #    name: Compress JMH Result
            #    command:
            #      cd build/reports/jmh && zip -r jmh-results.zip *
            - store_artifacts:
            #   path: build/reports/jmh/jmh-results.zip
                path: build/reports/jmh
                destination: jmh-results

workflows:
  version: 2
  build:
      jobs:
          - dependencies
          - build:
                requires:
                    - dependencies
  jmh:
      jobs:
          - hold:
                type: approval
          - dependencies:
                requires:
                    - hold
          - jmh:
                requires:
                    - dependencies
